# Cloudflare DNS Zones
# Auto-generated by cf-terraforming and cleaned up
# Account: The HOLE Foundation (1a25a792e801e687b9fe4932030cf6a6)

# ===========================================================================
# PRIMARY BUSINESS ZONE
# ===========================================================================

resource "cloudflare_zone" "theholetruth_org" {
  account_id          = var.cloudflare_account_id
  paused              = false
  plan                = "business"  # $200/month - verify if needed!
  type                = "full"
  vanity_name_servers = []
  zone                = "theholetruth.org"
}

# ===========================================================================
# FOUNDATION & ORGANIZATION ZONES (FREE)
# ===========================================================================

resource "cloudflare_zone" "theholefoundation_org" {
  account_id          = var.cloudflare_account_id
  paused              = false
  plan                = "free"
  type                = "full"
  vanity_name_servers = []
  zone                = "theholefoundation.org"
}

resource "cloudflare_zone" "holefoundation_org" {
  account_id          = var.cloudflare_account_id
  paused              = false
  plan                = "free"
  type                = "full"
  vanity_name_servers = []
  zone                = "holefoundation.org"
}

resource "cloudflare_zone" "holeoversight_org" {
  account_id          = var.cloudflare_account_id
  paused              = false
  plan                = "free"
  type                = "full"
  vanity_name_servers = []
  zone                = "holeoversight.org"
}

resource "cloudflare_zone" "holetrust_org" {
  account_id          = var.cloudflare_account_id
  paused              = false
  plan                = "free"
  type                = "full"
  vanity_name_servers = []
  zone                = "holetrust.org"
}

# ===========================================================================
# TRUTH PROJECT ZONES (FREE)
# ===========================================================================

resource "cloudflare_zone" "holetruth_org" {
  account_id          = var.cloudflare_account_id
  paused              = false
  plan                = "free"
  type                = "full"
  vanity_name_servers = []
  zone                = "holetruth.org"
}

resource "cloudflare_zone" "hole_truth_org" {
  account_id          = var.cloudflare_account_id
  paused              = false
  plan                = "free"
  type                = "full"
  vanity_name_servers = []
  zone                = "hole-truth.org"
}

resource "cloudflare_zone" "holetruthproject_org" {
  account_id          = var.cloudflare_account_id
  paused              = false
  plan                = "free"
  type                = "full"
  vanity_name_servers = []
  zone                = "holetruthproject.org"
}

resource "cloudflare_zone" "theholetruthelpaso_org" {
  account_id          = var.cloudflare_account_id
  paused              = false
  plan                = "free"
  type                = "full"
  vanity_name_servers = []
  zone                = "theholetruthelpaso.org"
}

# ===========================================================================
# RELATED PROJECT ZONES (FREE)
# ===========================================================================

resource "cloudflare_zone" "realjusticematters_org" {
  account_id          = var.cloudflare_account_id
  paused              = false
  plan                = "free"
  type                = "full"
  vanity_name_servers = []
  zone                = "realjusticematters.org"
}

resource "cloudflare_zone" "thepublicsinfo_org" {
  account_id          = var.cloudflare_account_id
  paused              = false
  plan                = "free"
  type                = "full"
  vanity_name_servers = []
  zone                = "thepublicsinfo.org"
}

resource "cloudflare_zone" "ai_watch_org" {
  account_id          = var.cloudflare_account_id
  paused              = false
  plan                = "free"
  type                = "full"
  vanity_name_servers = []
  zone                = "ai-watch.org"
}

# ===========================================================================
# PERSONAL/CONSULTING ZONES (FREE)
# ===========================================================================

resource "cloudflare_zone" "joeherrmann_com" {
  account_id          = var.cloudflare_account_id
  paused              = false
  plan                = "free"
  type                = "full"
  vanity_name_servers = []
  zone                = "joeherrmann.com"
}

resource "cloudflare_zone" "drjth_net" {
  account_id          = var.cloudflare_account_id
  paused              = false
  plan                = "free"
  type                = "full"
  vanity_name_servers = []
  zone                = "drjth.net"
}

resource "cloudflare_zone" "herrmann_consulting" {
  account_id          = var.cloudflare_account_id
  paused              = false
  plan                = "free"
  type                = "full"
  vanity_name_servers = []
  zone                = "herrmann.consulting"
}
